### ISSUE TITLE
Bug: MQTT entity name starts with the device name in your config - HA 2023.8 

### ISSUE THREAD

**Issue by Anto79-ops** [LAB02-Research/HASS.Agent#337] opened 2023-08-01 19:55 UTC
Hi,

There was a change about [MQTT naming](https://rc.home-assistant.io/integrations/mqtt#naming-of-mqtt-entities) for HA Core 2023.8 about not having device name in entity name. It seems HASS agent uses device name in the entity name, for example:

```
2023-08-01 07:48:57.836 WARNING (MainThread) [homeassistant.components.mqtt.mixins] MQTT entity name starts with the device name in your config {'availability_topic': 'homeassistant/sensor/ANTO/availability', 'icon': 'mdi:webcam', 'unique_id': '1004c0a3-9f4c-4cf3-95ba-2a91843c225f', 'device': {'identifiers': ['hass.agent-ANTO'], 'manufacturer': 'LAB02 Research', 'model': 'Microsoft Windows NT 10.0.19045.0', 'name': 'ANTO', 'sw_version': '2022.14.0', 'connections': []}, 'name': 'ANTO_HP_webcamactive', 'state_topic': 'homeassistant/binary_sensor/ANTO/ANTO_webcamactive/state', 'payload_off': 'OFF', 'payload_on': 'ON', 'payload_available': 'online', 'force_update': False, 'availability_mode': 'latest', 'enabled_by_default': True, 'payload_not_available': 'offline', 'encoding': 'utf-8', 'qos': 0}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes '_webcamactive'

```

All the mqtt entites generated by HASS agent generate this log.

**Comment by ABEIDO** [comment] 2023-08-02 20:47
Ive read the post from HA regrading this but im not really getting it fully. Saw your post ImSkully so im asking here.

If i understand correclty, is Hass.Agent not going to work after 2024.2.0 if Hass.Agent isnt updated to comply with this before that?

**Comment by Anto79-ops** [comment] 2023-08-02 20:52
it sounds like it wont break HASS agent, but rather duplicate the device name according to [Frenck](https://discord.com/channels/330944238910963714/427516175237382144/1135963276342214766)

It already removed the device name from the friendly name on my system, but it has not changed the entity itself.

**Comment by micium** [comment] 2023-08-02 22:10
same messages here:

MQTT entity name starts with the device name in your config {'availability_topic': 'homeassistant/sensor/XXXXXXXX/availability', 'icon': 'mdi:battery-high', 'unique_id': 'XXXXXXXX_battery_charge_remaining', 'device': {'identifiers': ['hass.agent-XXXXXXXX'], 'manufacturer': 'LAB02 Research', 'model': 'Microsoft Windows NT 10.0.19045.0', 'name': 'XXXXXXXX', 'sw_version': '2022.14.0', 'connections': []}, 'name': 'XXXXXXXX_battery Charge Remaining', 'state_topic': 'homeassistant/sensor/XXXXXXXX/XXXXXXXX_battery/XXXXXXXX_battery_charge_remaining/state', 'force_update': False, 'encoding': 'utf-8', 'qos': 0, 'payload_available': 'online', 'payload_not_available': 'offline', 'enabled_by_default': True, 'availability_mode': 'latest'}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes '_battery Charge Remaining'

**Comment by ImSkully** [comment] 2023-08-02 22:40
This should not be a breaking change when it does come into effect in 2024.2 so the deprecation warning is safe to ignore for HASS.Agent users.

It would be good to perhaps have the option to change the broadcasted entity name for sensors in the same way entity IDs can be provided.

**Comment by heilingbrunner** [comment] 2023-08-05 15:17
Excuse me, for me this is a breaking change ...
or what am i doing wrong ?? 

What can I do ? Thanks.

<img width="650" alt="ha-mqtt-warning-1" src="https://github.com/LAB02-Research/HASS.Agent/assets/1827209/089d05b9-9520-4d05-b9d8-8788b0ecb20a">

<img width="810" alt="ha-device-mqtt-hm800" src="https://github.com/LAB02-Research/HASS.Agent/assets/1827209/b938b54e-16d7-4039-bc54-efd203b26475">

**Comment by ImSkully** [comment] 2023-08-05 17:58
@heilingbrunner Your issue is unrelated to this warning.

**Comment by gitolicious** [comment] 2023-08-06 11:08
@heilingbrunner looks like these are AhoyDTU warnings, refer to the issue over there: https://github.com/lumapu/ahoy/issues/1066

**Comment by vladyspavlov** [comment] 2023-08-06 21:59
The easiest way to fix this is to do it yourself. You need to manually rename all of your sensor names to remove the device name from the sensor name:
<details>
<summary>Screenshot</summary>

![image](https://github.com/LAB02-Research/HASS.Agent/assets/16994749/cd1af44d-4ddb-4409-860a-039910ed625e)
</details>

So it should look like this:
<details>
<summary>Screenshot</summary>

![image](https://github.com/LAB02-Research/HASS.Agent/assets/16994749/f1b1d9ff-e3d2-4ffd-a6eb-e75447df51f2)
</details>

Restart Home Assistant and the warning caused by HASS.Agent entities should disappear. Or another way is to ignore it and wait until someone creates a PR, and it will be merged.

**Comment by zanix** [comment] 2023-08-07 03:33
I also tried to rename all the sensors and commands but it failed in an unexpected way.

If you have multiple computers set with the same names for the sensors and commands, you get a unique_id error in the Home Assistant logs and the duplicates are not listed and never show up.
I ended up having to rename everything with the device name again and live with the repair warning.

**Comment by amadeo-alex** [comment] 2023-08-07 09:16
Renaming the names will/can break the entity ids - sensor.<XYZ> within HA as with the current discovery payload, HA is creating entity IDs base on the name. You can leave it for now as it's only a deprecation warning.
A PR is in the works to address this.

**Comment by broyuken** [comment] 2023-08-08 15:31
the entity id names don't change, it's the friendly names that are changing. and changing the names worked perfectly for me. Now I just need to get my dafang cameras and espresence updated.

**Comment by ABEIDO** [comment] 2023-08-08 18:06
> I also tried to rename all the sensors and commands but it failed in an unexpected way.
> 
> If you have multiple computers set with the same names for the sensors and commands, you get a unique_id error in the Home Assistant logs and the duplicates are not listed and never show up. I ended up having to rename everything with the device name again and live with the repair warning.

Same here, the disk sensor failed and only one pf the machines with hass agent showed disk c. Also decided to go back and rename with devicename.

**Comment by danielbrunt57** [comment] 2023-10-13 03:48
I renamed my buttons and sensors in HASS Agent removing the device name from them and problem solved.

![image](https://github.com/LAB02-Research/HASS.Agent/assets/49846893/a4753b82-e9b9-45bb-8796-cbfc08e3044e)

![image](https://github.com/LAB02-Research/HASS.Agent/assets/49846893/1ee6e907-29f6-4022-990e-24829fd73ebd)

![image](https://github.com/LAB02-Research/HASS.Agent/assets/49846893/f4ccb2b9-4160-4ae3-98af-772d0230b8fa)

Alternative if you have more than 1 instance of the Agent deployed would be to change the sensor names somewhat so that they do not contain the device name yet still be unique across the Agent instances.

**Comment by Bodge-IT** [comment] 2023-11-15 13:55
I moved the device name to the end of command name and sensor names.  Seems to be OK so far.

**Comment by Anto79-ops** [comment] 2024-03-08 04:51
Fixed in 2.0.1 and up.

**Closed as completed** 2024-03-08 04:51 UTC

**Comment by ravngr** [comment] 2024-03-08 05:11
For anyone following this and was confused as I was (subscribed to the issue but not activly following the project), there's a fork under the new [hass-agent](https://github.com/hass-agent) org that's had some ongoing development since this repo/org appears to be dormant.

**Comment by bcutter** [comment] 2024-07-22 17:38
> Fixed in 2.0.1 and up.

Which "2.0.1"?

Latest release according to https://github.com/LAB02-Research/HASS.Agent/releases still is this:

![grafik](https://github.com/user-attachments/assets/25166a65-0389-4ae0-91a2-1b6c97c04786)

It's a joke or do I miss some GitHub mechanisms here?

I ran into the very same issue after updating HA almost ONE YEAR after this issue arrised for the first time (HA 2023.8) - and there still is no fix in a stable HASS agent release? Are you kidding?

![grafik](https://github.com/user-attachments/assets/71cb353f-cf1a-41e9-8d72-8e6d808d5331)

As I have more than one client running HASS agent, just removing the device name in hass agent sensor config is not a solution.

Maybe switching to the maintained fork as mentioned in https://github.com/LAB02-Research/HASS.Agent/issues/337#issuecomment-1985050154 is a proper future-proof "solution"...

**Comment by zanix** [comment] 2024-07-22 19:50
> > Fixed in 2.0.1 and up.
> 
> Which "2.0.1"?
> 
> Latest release according to https://github.com/LAB02-Research/HASS.Agent/releases still is this:
> 
> ![grafik](https://private-user-images.githubusercontent.com/13799156/351059325-25166a65-0389-4ae0-91a2-1b6c97c04786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Nzc0ODEsIm5iZiI6MTcyMTY3NzE4MSwicGF0aCI6Ii8xMzc5OTE1Ni8zNTEwNTkzMjUtMjUxNjZhNjUtMDM4OS00YWUwLTkxYTItMWI2Yzk3YzA0Nzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE5Mzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlY2Q5ZDczZGQ0ZDUxZGI1OGY4ODdmYzY1YTdhYTk3MjU4MTRhNzc4YzZmNWIwMDk1YzViM2U1Mjc5YjZmMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2AGUPBm9HuEQVoUslKh1kHcH_jEaPVwWUNFhT83kTdI)
> 
> It's a joke or do I miss some GitHub mechanisms here?
> 
> I ran into the very same issue after updating HA almost ONE YEAR after this issue arrised for the first time (HA 2023.8) - and there still is no fix in a stable HASS agent release? Are you kidding?
> 
> ![grafik](https://private-user-images.githubusercontent.com/13799156/351059758-71cb353f-cf1a-41e9-8d72-8e6d808d5331.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Nzc0ODEsIm5iZiI6MTcyMTY3NzE4MSwicGF0aCI6Ii8xMzc5OTE1Ni8zNTEwNTk3NTgtNzFjYjM1M2YtY2YxYS00MWU5LThkNzItOGU2ZDgwOGQ1MzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE5Mzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMGM2OGY4NTk5MWY2ZDM4NDU5OGVjMzA5NjA4MDcyNWYyMTg2OWI3YzMzZmFiMTZiZGFiZGY0Mjg1YzQ5MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uWwQ8_ZLF7-BnAJD2kelpddqiEBlnlf_6O-SaBs0rGw)
> 
> As I have more than one client running HASS agent, just removing the device name in hass agent sensor config is not a solution.
> 
> Maybe switching to the maintained fork as mentioned in [#337 (comment)](https://github.com/LAB02-Research/HASS.Agent/issues/337#issuecomment-1985050154) is a proper future-proof "solution"...

They are referring to the fork
https://github.com/hass-agent/hass.agent

**Comment by bcutter** [comment] 2024-07-22 20:06
I know and I have now switched all my clients to that forked version. Event it's "only" the client component (HA integrations like HASS.Agent can stay untouched according to https://www.hass-agent.io/latest/getting-started/installation/#migration-from-pre-200) it was a lot of work to remove the duplicates of these sensors:
- batterie_charge_remaining
- batterie_charge_remaining_percentage
- batterie_charge_status
- batterie_full_charge_lifetime
- batterie_powerline_status
- speicher_total_disk_count

...which are not all existing sensors, so in MQTT plenty of topics still exist with the old `devicename_sensorname` setup and only those listed above got a new topic name `deviceUniqueID_sensorname`.

Wondering what about all the remaining ones?

Not sure what the forked version did on this. I can only see when editing existing sensors which have a device name in its name, it gives an information - that's it.
![grafik](https://github.com/user-attachments/assets/49c58d71-9dbb-4654-8d2c-3bfaf7240138)

I'll check if HA will continue to complain - I think so...

**Comment by pabloaugusto** [comment] 2024-07-22 20:34
> I know and I have now switched all my clients to that forked version. Event it's "only" the client component (HA integrations like HASS.Agent can stay untouched according to https://www.hass-agent.io/latest/getting-started/installation/#migration-from-pre-200) it was a lot of work to remove the duplicates of these sensors:
> 
> * batterie_charge_remaining
> * batterie_charge_remaining_percentage
> * batterie_charge_status
> * batterie_full_charge_lifetime
> * batterie_powerline_status
> * speicher_total_disk_count
> 
> ...which are not all existing sensors, so in MQTT plenty of topics still exist with the old `devicename_sensorname` setup and only those listed above got a new topic name `deviceUniqueID_sensorname`.
> 
> Wondering what about all the remaining ones?
> 
> Not sure what the forked version did on this. I can only see when editing existing sensors which have a device name in its name, it gives an information - that's it. ![grafik](https://private-user-images.githubusercontent.com/13799156/351098804-49c58d71-9dbb-4654-8d2c-3bfaf7240138.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODA0NzgsIm5iZiI6MTcyMTY4MDE3OCwicGF0aCI6Ii8xMzc5OTE1Ni8zNTEwOTg4MDQtNDljNThkNzEtOWRiYi00NjU0LThkMmMtM2JmYWY3MjQwMTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIwMjkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MzYyMmU5OTJjMTVlNzgzYWVlYWVmZDVlNTI4YjI3MGZlMGQyOTQzNjA5NTQ3ZDUwOTFlZTE4MGQ2ZmNlM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZj5rv5DxwwhL68ydlrQb7AN90CoPWbhw9OpeiXgpIM)
> 
> I'll check if HA will continue to complain - I think so...

Oh my goodness, I didn't realize some people were paying for this free tool! Please dev team, fix this huge problem that is disrupting this paying customer's life ASAP!!! He pays for this, so he can demand the resolution of bugs quickly and completely! Return to work NOW and fix it!!!!

**Comment by bcutter** [comment] 2024-07-22 23:05
I don't see why one would post such non-contributing rubbish to a factual report.
I'd recommend the mods to mute your post as it contributes absolutely nothing. Have a great day.

**Comment by tomlut** [comment] 2024-07-22 23:15
Have you not been listening? 

There are no mods.

This repository is dead.

This issue is also closed. 

The picture above is inaccurate, you are actually flogging a dead horse. 

![748](https://github.com/user-attachments/assets/8b95e017-f5cf-4175-8c7c-0fb287381fad)

**Comment by bcutter** [comment] 2024-07-22 23:18
Yes I got that. Seems to be an invitation for some folks (like @pabloaugusto) to behave like in the wild west. I'm out of here.

**Comment by tomlut** [comment] 2024-07-22 23:22
![bd0748ad-7c88-4805-b9a4-9d401577e488_text](https://github.com/user-attachments/assets/49499087-6da8-4146-8905-a05539aea2a0)

**Comment by pabloaugusto** [comment] 2024-07-22 23:27
> Yes I got that. Seems to be an invitation for some folks (like @pabloaugusto) to behave like in the wild west. I'm out of here.

Free cry airdrop! EnJOY yourself
