### ISSUE TITLE
Bug: Chinese in active window is shown ??

### ISSUE THREAD

**Issue by GHTGXL** [LAB02-Research/HASS.Agent#217] opened 2022-11-18 09:56 UTC
Please make sure your bug isn't already listed on HASS.Agent's issue tracker:

https://lab02research.youtrack.cloud/

There's a list of open bugs & features on the right. On the left you can see what's being worked on, what's planned and what's ready for the next release.

If you're not sure, don't worry, just go ahead and we'll discuss :)

----

**Describe the bug**
Chinese in active window is shown ??

**To Reproduce**
1. Set language to traditional Chinese
2. Go to Home
3. Google chrome shows home include 總覽
4. Wait activewindow to update
5. activewindow show 總覽 to ??

or 

1. open Simplified Chinese website
2. Wait activewindow to update
3. Chinese shows ?? in activewindow

**Expected behavior**
It should show 總覽 in activewindow, not ?? / or deliver the Chinese word in activewindow.

**Screenshots**

![Snipaste_2022-11-18_17-45-46](https://user-images.githubusercontent.com/83491024/202672004-53af8dde-116b-436b-b31d-1278aedd5c8d.png)

![Snipaste_2022-11-18_17-47-14](https://user-images.githubusercontent.com/83491024/202672287-d5c2fde3-d06d-43b3-a83b-c5fb82474265.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![Snipaste_2022-11-18_17-51-13](https://user-images.githubusercontent.com/83491024/202673127-19acfb46-18e5-479f-8bb5-ed2ef08ff932.png)

 - Windows' UI language:  
![Snipaste_2022-11-18_17-52-47](https://user-images.githubusercontent.com/83491024/202673553-15264e41-ca50-4a3e-84c7-d965967f347b.png)

 - HASS.Agent version:  2022.20.0.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`. If you want, you can mail them to lab02research@outlook.com
[logs.zip](https://github.com/LAB02-Research/HASS.Agent/files/10040211/logs.zip)
I have not turn on Satellite Service sensor and commands.

**Comment by GHTGXL** [comment] 2022-11-20 18:51
Oddly I install 2022.14.0 on another pc, that PC Chinese character is working fine.

**Comment by LAB02-Admin** [comment] 2022-11-22 09:02
That's weird. Are you sure both devices have the same UI languages installed/set? And did you try restarting HASS.Agent after changing the language (since it partially loads it at startup), or even reboot Windows.

Otherwise, could you please provide the following so I can reproduce:

- Screenshot of Windows' installed languages
- Site used

**Comment by GHTGXL** [comment] 2022-11-22 15:14
> That's weird. Are you sure both devices have the same UI languages installed/set? And did you try restarting HASS.Agent after changing the language (since it partially loads it at startup), or even reboot Windows.
> 
> Otherwise, could you please provide the following so I can reproduce:
> 
> * Screenshot of Windows' installed languages
> * Site used

Before I reported this bug, Both PC were not in the same language, Has ??? One Was Chinese(Simplified), Japanese, and English(US), and another didn't have ??? is Chinese(Simplified), But even trying to set has the ??? PC to only have Chinese(Simplified), Still the same, Swap the incoming mode, same, swap to edge, same, restart HASS.Agent, same.

This does not have ??? PC.
![IMG_2022-11-22-22-53-32-119](https://user-images.githubusercontent.com/83491024/203349710-aebcd119-38bf-4bd7-a411-f9c114f1685b.jpg)

This does have ???

![Snipaste_2022-11-22_23-11-58](https://user-images.githubusercontent.com/83491024/203350134-36841707-a1fa-42a3-a3e0-d4f854a5e352.png)

Test Site: sspai.com

**Comment by GHTGXL** [comment] 2022-11-22 16:10
By the way, I update the system of Have ??? pc. But still the same.

![Snipaste_2022-11-23_00-09-45](https://user-images.githubusercontent.com/83491024/203364036-ec34707b-005d-453a-b3bb-4758fc6996e7.png)

**Comment by GHTGXL** [comment] 2022-12-03 00:56
Ok, I know what happens, Is Unicode, for some reason, I change the ??? pc to use English Unicode, But because I use Chinese, so hass.agent show ???. Now is fixed. so should I close this issue?

**Comment by LAB02-Admin** [comment] 2022-12-16 16:06
Sorry for the late reply @GHTGXL, been busy. If this works for you, you cna close the issue and I'll add it to the docs in case someone else encounters it :)

**Closed** 2022-12-16 17:16 UTC
Labels: bug

**Comment by GHTGXL** [comment] 2022-12-16 17:17
Right now after I changed to Chinese, Everything is working.
