### ISSUE TITLE
Error trying to bind the api to port 5115

### ISSUE THREAD

**Issue by mrLeonTheMaster** [LAB02-Research/HASS.Agent#194] opened 2022-10-23 12:14 UTC
Please make sure your bug isn't already listed on HASS.Agent's issue tracker:

https://lab02research.youtrack.cloud/

There's a list of open bugs & features on the right. On the left you can see what's being worked on, what's planned and what's ready for the next release.

If you're not sure, don't worry, just go ahead and we'll discuss :)

----

**Describe the bug**
When starting hass.agent i get error "Error trying to bind the api to port 5115"

**To Reproduce**
1. Start "hass.agent"
2. See error

**Expected behavior**
The local api to work

**Screenshots**
![image](https://user-images.githubusercontent.com/78276856/197391473-c94cfdc2-1587-4012-aa4b-96981a4b5b4b.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 22621.675
 - Windows' UI language: Polish
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [ ] Installed via installer
 - [x] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
I am running hass.agent as admin

**Logs**
(https://github.com/LAB02-Research/HASS.Agent/files/9846526/2022-08-24.HASS.Agent_20220824.log)

**Comment by mrLeonTheMaster** [comment] 2022-10-23 13:13
@LAB02-Admin

**Comment by youseeus** [comment] 2022-10-25 13:14
Duplicate of #185

**Closed** 2022-10-26 14:17 UTC
