### ISSUE TITLE
Bug: Sleep command doesnt invoke Windows to sleep

### ISSUE THREAD

**Issue by defisit** [LAB02-Research/HASS.Agent#145] opened 2022-08-18 12:49 UTC
----

**Describe the bug**

Configuring the Sleep command goes fine. Entity appears in HA. However, invoking it from HA doesnt put the Windows 10 machine in sleep. I have verified through Windows command that Hibernation is disabled. (powercfg /hibernate off)

**To Reproduce**

Invoking the button entity on HA front-end does show it has been pressed, but nothing happens on Windows. Other commands e.g.  Lock work fine from hass.agent. I dont see anything being written to the log when pressing the button on the HA front-end.

**Expected behavior**

Expected the machine to go to Sleep.

**Screenshots**
![image](https://user-images.githubusercontent.com/61313374/185398101-d4a0112f-f73c-46f3-80f2-f17c0ad28878.png)
![image](https://user-images.githubusercontent.com/61313374/185377292-d21a6a15-ce1b-4f93-a8f7-731bd8ef7fdd.png)
![image](https://user-images.githubusercontent.com/61313374/185398375-27753702-71c0-4e70-87ef-11e4dc40fc48.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 19043.1889
 - Windows' UI language: English
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`. If you want, you can mail them to lab02research@outlook.com

2022-08-18 12:44:48.042 +02:00 [INF] [SYSTEM] Application shutdown complete
2022-08-18 12:44:50.316 +02:00 [INF] [MAIN] Extended logging enabled
2022-08-18 12:44:50.323 +02:00 [INF] [SETTINGS] Config storage path: C:\Users\<removed>\AppData\Roaming\LAB02 Research\HASS.Agent\config
2022-08-18 12:44:50.435 +02:00 [INF] [SETTINGS] Configuration loaded
2022-08-18 12:44:50.439 +02:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2022-08-18 12:44:50.709 +02:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2022-08-18 12:44:50.743 +02:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2022-08-18 12:44:50.755 +02:00 [INF] [SETTINGS_SENSORS] Loaded 3 entities
2022-08-18 12:44:50.760 +02:00 [INF] [MQTT] Identifying as device: <removed>
2022-08-18 12:44:50.760 +02:00 [INF] [NOTIFIER] Ready
2022-08-18 12:44:50.761 +02:00 [INF] [SERVICE] Local install path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2022-08-18 12:44:50.761 +02:00 [INF] [MEDIA] Ready
2022-08-18 12:44:50.763 +02:00 [INF] [LOCALAPI] Initializing ..
2022-08-18 12:44:50.798 +02:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2022-08-18 12:44:50.801 +02:00 [INF] [MQTT] Connecting ..
2022-08-18 12:44:50.882 +02:00 [INF] [MQTT] Connected
2022-08-18 12:44:50.894 +02:00 [INF] [HASS_API] Home Assistant version: 2022.8.5
2022-08-18 12:44:51.157 +02:00 [INF] [LOCALAPI] listening on port 5115
2022-08-18 12:44:51.450 +02:00 [INF] [HASS_API] System connected with http://homeassistant.lan:8123
2022-08-18 12:44:52.813 +02:00 [INF] [MQTT] Initial registration completed
2022-08-18 12:47:05.879 +02:00 [FTL] [PROGRAM] FirstChanceException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2022-08-18 13:01:06.612 +02:00 [FTL] [PROGRAM] FirstChanceException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.<CheckUsabilityOnScavenge>g__ReadAheadWithZeroByteReadAsync|44_0()
2022-08-18 13:41:22.282 +02:00 [ERR] [NET] [ConnectionRefused] No connection could be made because the target machine actively refused it.
2022-08-18 13:41:35.992 +02:00 [INF] [HASS_API] Server recovered from failed state
2022-08-18 13:51:08.614 +02:00 [FTL] [PROGRAM] FirstChanceException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.<CheckUsabilityOnScavenge>g__ReadAheadWithZeroByteReadAsync|44_0()

**Comment by LAB02-Admin** [comment] 2022-08-18 13:38
Hi @defisit,

That's unfortunate :( But I don't know what could be the reason. It's a tried & tested command, using a simple Windows command (`Rundll32.exe powrprof.dll,SetSuspendState 0,1,0`). Could be some setting blocking it somewhere.

You can make a custom command, and use [NirCmd](http://www.nirsoft.net/utils/nircmd.html) and invoke it with `nircmd standby`.

**Comment by defisit** [comment] 2022-08-18 14:02
ok. Attempted to run that command but nothing happens. Attempted to run 'nircmd standy' with or without force, nothing. Are there elevated privileges required for the Windows to go in sleep mode? This particular Windows machine has EPM software installed. That could potentially be blocking commands. However, both the Rundll32.exe .... and NirCmd dont invoke an elevated prompt by the EPM application.

**Comment by LAB02-Admin** [comment] 2022-08-18 14:26
And the start menu's sleep button works?

**Comment by LAB02-Admin** [comment] 2022-08-18 14:31
You can try [PsShutdown](https://docs.microsoft.com/en-au/sysinternals/downloads/psshutdown): `psshutdown -d -t 0`

**Comment by defisit** [comment] 2022-08-19 08:55
> You can try [PsShutdown](https://docs.microsoft.com/en-au/sysinternals/downloads/psshutdown): `psshutdown -d -t 0`

Psshutdown does not work either. "Error shutting down system: The request is not supported"

Using the Startmenu sleep button works just fine. There's something on the device thats blocking these commands, either a GPO or EPM software. I'll look into that with someone from IT support.

**Comment by LAB02-Admin** [comment] 2022-08-22 09:07
Guess so yea. I'm closing this as there's not much I can do, but please let me know if you find the cause (so I can test for it and create an error msg if other users have that config as well. Thanks, and good luck :)

**Closed by LAB02-Admin** 2022-08-22 09:07 UTC

**Comment by GarnetSunset** [comment] 2022-09-03 20:30
Can confirm nircmd does indeed work

**Comment by heisenberg2980** [comment] 2023-09-19 17:19
@defisit having the same issue, did you find out what was stopping these commands to work?

**Comment by defisit** [comment] 2023-09-20 11:48
> @defisit having the same issue, did you find out what was stopping these commands to work?

No, but I expect the EPM software on my (Corporate managed) device blocks those. I didn't bother to look any further.
