### ISSUE TITLE
Bug: sensors stop working if HA is restarted and HASS.agent isn't

### ISSUE THREAD

**Issue by VNRARA** [LAB02-Research/HASS.Agent#51] opened 2022-04-20 23:12 UTC
A restart of HA will NOT automatically reconnect the sensors after a reboot. Only a reboot of HASS.Agent will fix this. 

[logs.zip](https://github.com/LAB02-Research/HASS.Agent/files/8525969/logs.zip)

**Comment by LAB02-Admin** [comment] 2022-04-21 09:41
Hi @VNRARA,

Thank you for your bug report, and attaching the logs (love it when that gets done without asking).

I've been trying to reproduce your issue, as there are systems in place that should prevent this - and there are mentions in your logs that HASS.Agent did reconnect after a failure.

For starters, I had to update my staging system, so that meant it went offline for a bit. HASS.Agent fell into alternating between connecting/failed mode, as expected (please ignore the notification api state, it's not enabled on my staging setup):

![image](https://user-images.githubusercontent.com/81011038/164422771-60267997-a993-43d3-9105-577d937cfde1.png)

When HA came back online, both reconnected (took a minute or so):

![image](https://user-images.githubusercontent.com/81011038/164422847-3be87f48-747e-4a12-bfca-60914264445d.png)

For test 2, I completely shutdown the staging HA environment. In this test, HASS.Agent demonstrated the same behavior: when I started HA after about 10 minutes, both the API and MQTT reconnected.

For test 3, I shutdown the staging HA environment, shutdown HASS.Agent, and then started HASS.Agent (so it wouldn't be able to connect initially). After 5 minutes I started HA, and this resulted in interesting behavior: after a short while MQTT connected, however the API did not:

![image](https://user-images.githubusercontent.com/81011038/164422897-6bc658c2-de89-4a43-998d-a6e174cdb95f.png)

So this is a bug, and I'll fix it: [hassagent-47](https://lab02research.youtrack.cloud/issue/hassagent-47)

However, regarding your issue: sensors and commands worked just fine. Even after test 3, I tested both. That would make sense, because they use MQTT - the HA API is only used for fetching entities and their state for the Quick Actions.

Could you please give me some more info, so I can more accurately try to reproduce:

- What's the sequence that caused it (HASS.Agent is and stays active, HA goes down, HA goes back up, something like that)
- Do you have both sensors and commands configured
- Is everything working OK normally
- Exactly what time did the situation start (so we can pinpoint in the logs)
- How did you notice the sensors/commands stopped working (through the system status main screen, or missing updates, or..?)

Also, if you have the time, could you please install the latest beta (no need to uninstall anything, you can just run it):

https://github.com/LAB02-Research/HASS.Agent/releases/download/b2022.11.2/HASS.Agent.Installer.exe

This one creates seperate logs for the task-specific child applications (like 'restart hass') so you won't get the 'log file already in use' errors. You don't have to, it's not likely the beta will fix your bug.

Thank you very much for your time!

**Comment by VNRARA** [comment] 2022-04-21 10:53
Thanks for getting back to me so quick: I was able to reproduce and screengrab and some more logs:

I reboot HA:

![image](https://user-images.githubusercontent.com/3942672/164442678-50798d94-0d30-4661-91cd-61783aca101e.png)

It starts loading everything back up:

![image](https://user-images.githubusercontent.com/3942672/164442763-ebbcfd09-55dc-41ab-b078-b80318644282.png)

Once started my custom sensors are not available: 

![image](https://user-images.githubusercontent.com/3942672/164442905-da6416b5-c467-4abe-895a-f9afb59b0009.png)

Resolution X and Y are unknown untill I restore the sensors.

![image](https://user-images.githubusercontent.com/3942672/164443001-210a5f8f-e086-41bb-9bed-4fa810440f26.png)

Resaving the sensor: 

![image](https://user-images.githubusercontent.com/3942672/164443166-4cd25b79-7c9d-4c17-83c8-fb4d8b100395.png)

![image](https://user-images.githubusercontent.com/3942672/164443249-950e12ad-efe5-4b0d-bc19-3c730b91c9f1.png)

And it works again:

[[2022-04-21] HASS.Agent_20220421_009.log](https://github.com/LAB02-Research/HASS.Agent/files/8530258/2022-04-21.HASS.Agent_20220421_009.log)

**Comment by LAB02-Admin** [comment] 2022-04-21 11:02
Thanks, very helpful! 

The issue here is that HASS.Agent thinks as follows: _the sensor's value hasn't changed, so I don't need to send it again_. There is a mechanism that resends all values after a reconnection, but that doesn't always work because the timing needs to be precise.

I'm working on an alternative system, that uses the HA API to constantly check whether HASS.Agent's last known sensor value match with the value that HA has for that sensor. If they don't match, HASS.Agent will resend the value. That way, no matter what the underlying cause is, it'll always stay in sync.

Until then, you can use a `PublishAllSensors` command:

![image](https://user-images.githubusercontent.com/81011038/164444578-54f8256c-3ed6-4478-88a7-c5716601820d.png)

You can set it to trigger after a HA restart, using the `platform start` trigger in combination with a short delay:

```yaml
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay:
        minutes: 2
```

If you use the Satellite Service, you can create the same command for that as well. So just trigger both commands from your auomation.

Hopefully this'll fix it for you until I have the backup system ready (won't be until next release).

**Comment by LAB02-Admin** [comment] 2022-04-23 10:12
Closing this for now, but feel free to reopen if it doesn't work for you!

You can follow the new system I mentioned in ticket [#41]

**Closed by LAB02-Admin** 2022-04-23 10:12 UTC
Labels: bug
