### ISSUE TITLE
Feature: Add a sensor tracking Mic/Camera usage (via the Registry)

### ISSUE THREAD

**Issue by Nedevski** [LAB02-Research/HASS.Agent#251] opened 2023-01-11 14:54 UTC
**Is your feature request related to a problem? Please describe.**
I am working from home together with my girlfriend. Currently the way we communicate when we are in a meeting is with waving and kicking under the desk.
I would like to automate this by having two smart bulbs (or a LED strip or whatever) to turn on in red color when someone is in a meeting. The automations based on this are endless, but the core information needed is still the same - which app uses the mic and camera currently?

**Describe the solution you'd like**
Ideally the app should support adding two sensors - for webcam and microphone. When the device starts getting used - flag goes up. When it's no longer getting used - flag down. That's all.

I've just found that Windows updates the registries with information on which app started using which permission, including timestamps for started/ended. The locations are:
`Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam\*`
`Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone\*`

There you have folders for all Windows pre-packaged apps, as well as a `NonPackaged` folder where you will find everything else - Chrome, Teams, Discord, etc.

I've also found [this link](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regnotifychangekeyvalue) to the MS docs for a function that allows you to monitor the registry. I'm guessing there should be watchers added for each key for each app for both mic and camera, so I'm not sure if this will be too heavy and viable at all, but it's an idea.

**Describe alternatives you've considered**
Any other realtime monitoring tool/library might work for this, after which I guess it's just adding another Host sensor, the same as the CPU/GPU usage.

**Additional context**
I'm a .NET dev myself and I would really like to just start digging through it immediately, but unfortunately I'm at work. I'm using this request as a `TODO:` for me later (or for someone else if I don't have free time soon).

**Comment by jordandrako** [comment] 2023-01-13 19:04
Seems to be a duplicate of #249 I opened a few days ago, so this is definitely a highly sought feature.

In the hass-workstation-service project, I made a recursive function to loop through those registry keys and return a list of processes, so this is the correct path. I'll add that returning all processes has the potential to max out the 255 character limit of a home assistant sensor state, so making adding the processes to state attributes would be preferred.

I would make a PR but I'm not a .NET dev and can't figure out how to access the source code of the webcam/mic sensors.

**Comment by LAB02-Admin** [comment] 2023-01-14 09:33
Hey @Nedevski and @jordandrako, there's already a sensor that does this: MicrophoneProcess and WebcamProcess. However, it currently only reports one process. If you do want to jump in, you could make a MicrophoneProcesses sensor that sends an array of processes. 

Here's some info on how to start developing: https://hassagent.readthedocs.io/en/latest/development/introduction/

**Closed** 2023-01-14 12:02 UTC
