### ISSUE TITLE
Enhancement: notify user of manager state when editing sensors/commands

### ISSUE THREAD

**Issue by amplitur** [LAB02-Research/HASS.Agent#30] opened 2022-01-31 11:59 UTC
Release v2022.1.24

The sensor values are not being updated while the Local Sensors/Sensors Config window is open. In this case I was continuously moving my mouse and the update interval for the sensor is five seconds - the value should not have increased above five seconds.

![image](https://user-images.githubusercontent.com/28072694/151788552-3f62662f-0786-4928-9a8f-ac8a2b18ef25.png)

**Comment by LAB02-Admin** [comment] 2022-01-31 21:26
Hi @amplitur, that is by design. When you open the sensor config screen, the sensor manager stops processing your sensors, same for commands. When you store them, it syncs your modifications and continues. This is to prevent data corruption.

Is it something you'd want changed?

**Comment by amplitur** [comment] 2022-02-02 12:00
If you keep this design, it would be good to notify the user that currently configured sensors are suspended while the user is modifying the configuration and will only resume (with the new configuration) once the user clicks "store and activate sensors" (or clicks on the "x" to close the configuration window without changes to configuration).

Alternatively, the old configuration could stay active and being processed until that moment in time when the user clicks on "store and activate".

**Comment by LAB02-Admin** [comment] 2022-02-13 12:02
Fixed in [latest beta](https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.2.13), it'll now just keep working until the exact moment you store your sensors/commands.

**Closed by LAB02-Admin** 2022-02-13 12:02 UTC
Labels: enhancement
