### ISSUE TITLE
Bug: Problem with Slider and monitorwake

### ISSUE THREAD

**Issue by mcfly2283** [LAB02-Research/HASS.Agent#216] opened 2022-11-17 22:00 UTC
Is set a custom state of a cover via custom:slider-entity-row in my Chrome-Kiosk-Browser (Windows 11) in the Main-View of my Touch-Wallpanel.
The cover was set to its new position, for example from 60% to 50%. Everything is fine.

But, when my Monitor was set to Sleep-Mode and Waked-Up via predefined "monitorwake", the cover moves up to its previous postion -> 60% The Slider ist also showing the old state of 60%. 

HASS.Agent is using an "arrow up" to Wake-Up the Screen. If the Last Touch-Point was focused on the slider - it will move up one step.

It would be less problematic if there is another Predefined-Key for the WakeUp-Command. 
Now im using [ALT] with the Keypress-Function, but this was a big trap for me :)

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by LAB02-Admin** [comment] 2022-11-22 08:38
Yep known issue, sorry! It's on my todo shortlist: [[hassagent-141](https://lab02research.youtrack.cloud/issue/hassagent-141)]

**Comment by LAB02-Admin** [comment] 2022-11-22 08:39
Closing this, duplicate of #149

**Closed by LAB02-Admin** 2022-11-22 08:39 UTC
