### ISSUE TITLE
Feature: WebcamProcessSensor

### ISSUE THREAD

**Issue by DennisGaida** [LAB02-Research/HASS.Agent#108] opened 2022-07-05 22:27 UTC
**Is your feature request related to a problem? Please describe.**
Windows Hello enabled cameras are also registered as webcams in Windows, meaning whenever you authenticate to your Windows machine using Windows Hello camera (infrared), all the automations based on webcam activity are triggered.

**Describe the solution you'd like**
When the webcam is active I want to know what process is using it. Many use cases for this:

* different automations based on the program I am using (e.g. Zoom/Teams call vs. Windows Camera app)
* Windows Hello authentication via camera is always leveraged using svchost.exe or SensorDataService.exe - If I would know that these processes are currently triggering the webcam, I can exclude automations - same issue here: https://github.com/sleevezipper/hass-workstation-service/issues/92

**Describe alternatives you've considered**
Use [HASS Workstation Service](https://github.com/sleevezipper/hass-workstation-service)

**Comment by LAB02-Admin** [comment] 2022-07-06 07:24
Hey @DennisGaida, good point! That'll really increase usability :)

Created a ticket for this request: [hassagent-120](https://lab02research.youtrack.cloud/issue/hassagent-120).
I'm closing this GitHub ticket, not because I'm not doing it, but to keep everything centralised. I'll post back here when it's implemented :)

**Closed by LAB02-Admin** 2022-07-06 07:24 UTC

**Comment by LAB02-Admin** [comment] 2022-08-12 15:22
Added in the latest beta: https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta2

**Comment by LAB02-Admin** [comment] 2022-08-14 07:14
> Do you want comments on the feature here or somewhere else since this issue is closed?

Here is fine :)

> Currently isn't ideal in the beta. Microsoft Teams shows up as NonPackaged which is completely missing the exe name.

I'll tweak the parser, thanks for letting me know.

> Windows Camera shows up as WindowsCamera with the beta, but actually is Microsoft.WindowsCamera_8wekyb3d8bbwe in the registry.

Yea that is by design. WindowsCamera is a lot more readable, so I parse the actual name from the reg entry.

**Comment by LAB02-Admin** [comment] 2022-08-16 11:32
That's great stuff @DennisGaida, thank you!

**Comment by dimatx** [comment] 2022-09-19 18:57
@LAB02-Admin, with 2022.13.0-beta3 [BETA], Microsoft Teams shows up as "non-packaged" for the WebcamProcess sensor as does Windows authentication/login prompt via Windows Hello. Is that expected behavior for this version?

**Comment by LAB02-Admin** [comment] 2022-09-19 20:36
No, I think I forgot to add the actual fix :x I'll re-release this beta later and let you know

**Comment by dimatx** [comment] 2022-09-20 02:21
Thanks :) Appreciate the fast turnaround!

**Comment by LAB02-Admin** [comment] 2022-09-21 08:32
I've re-released beta3: https://github.com/LAB02-Research/HASS.Agent/releases/download/2022.13.0-beta3/HASS.Agent.Installer.exe

You can just run the installer again, no need to uninstall. Let me know how it goes!

**Comment by LAB02-Admin** [comment] 2022-09-21 14:15
Looking at the code, he gets both keys - it depends under what user the service runs whether that's useful. But I'll enable it for hass.agent's service, doesn't require extra coding anyway and users can decide for themselves. 

At any rate, glad it's working for you, let me know whenever it might need tweaks :)

**Comment by dimatx** [comment] 2022-09-21 19:02
Works for me also. Thanks for the re-release and for your contributions in general!
